keys:
  # users
  - &spencer E2E7C16A57C8F7794F0EFDA16A3F9D0EB5A1B8D8
  # hosts
  - &magnolia age1mljt7tad3jkuju45m2np9vlq8qesy83403u49qm9pax4x5wwudjqvftuvy
  - &oak age1rjdsmpycnvte7aw8s8v5z3y7qgpc0aujs350pr54yeq6d077qg3se4zs05
  - &redbud age14w3xdtk9008g35r6rgrnwk03wevu88e6tfn0qfur449avhynjeps3znnud
  - &warden age1w68rhqzqykfary5acq89w868pz7nyttpe39k588a00dz5fhhd3lq9fgh7s
creation_rules:
  - path_regex: hosts/oak/secrets.ya?ml$
    key_groups:
      - age:
          - *oak
        pgp:
          - *spencer
  - path_regex: hosts/redbud/secrets.ya?ml$
    key_groups:
      - age:
          - *redbud
        pgp:
          - *spencer
  - path_regex: hosts/warden/secrets.ya?ml$
    key_groups:
      - age:
          - *warden
        pgp:
          - *spencer
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *magnolia
          - *oak
          - *redbud
          - *warden
        pgp:
          - *spencer
