keys:
  # users
  - &spencer E2E7C16A57C8F7794F0EFDA16A3F9D0EB5A1B8D8
  # hosts
  - &magnolia age1mljt7tad3jkuju45m2np9vlq8qesy83403u49qm9pax4x5wwudjqvftuvy
  - &oak age1hsmsx3jpmlw56e638l0wx62lhtaz7kanr9az4yq7mzv074x8cayqwrgxe3
  - &redbud age14w3xdtk9008g35r6rgrnwk03wevu88e6tfn0qfur449avhynjeps3znnud
  - &warden age19qp3wj8v5zksrqygezcz9twk4dsgg27dnqyjlfskw7pd63akys7q26v0gs
creation_rules:
  - path_regex: hosts/oak/secrets.ya?ml$
    key_groups:
      - age:
          - *oak
        pgp:
          - *spencer
  - path_regex: hosts/redbud/secrets.ya?ml$
    key_groups:
      - age:
          - *redbud
        pgp:
          - *spencer
  - path_regex: hosts/warden/secrets.ya?ml$
    key_groups:
      - age:
          - *warden
        pgp:
          - *spencer
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *magnolia
          - *oak
          - *redbud
          - *warden
        pgp:
          - *spencer
