#!/usr/bin/env bash

VM_DOMAIN=$1
if [ ! -n "$VM_DOMAIN" ]; then
  echo -e "vm domain is required, ./dumpxml.sh %DOMAIN%"
  exit 1
fi

(
  echo "<!-- File generated by '$0 $@' -->"
  virsh -c qemu:///system dumpxml $VM_DOMAIN
) > "$VM_DOMAIN".xml
