{
 "title": "Hosts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Last Seen Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$C - $B", "type": "math" }
   ]
  },
  {
   "title": "NixOS Build Id",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk by(instance) (1, node_os_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zpool Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk by(instance, zpool) (1, node_zfs_zpool_state)",
     "legendFormat": "{{instance}}:{{zpool}}:{{state}}"
    }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (node_systemd_units{state=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_network_transmit_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_network_receive_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Temperature",
   "type": "timeseries",
   "description": "Max temperature (C) across all sensors for each instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by(instance) (node_hwmon_temp_celsius)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1m load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum by(instance) (node_load1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Smokeping Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(host) (smokeping_send_errors_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (smokeping_receive_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {},
    {
     "expr": "sum by(instance) (node_softnet_dropped_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_memory_MemFree_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_memory_Cached_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}